/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.jsnu.laundry.model;

import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType LaundryUser.
 *
 * @since 2026-09-11
 */
@PrimaryKeys({"uid"})
@Indexes({"idx_installId:installId"})
public final class LaundryUser extends CloudDBZoneObject {
    private String uid;

    private String installId;

    private Date createdAt;

    private Date lastActiveAt;

    private String appVersion;

    public LaundryUser() {
        super(LaundryUser.class);
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUid() {
        return uid;
    }

    public void setInstallId(String installId) {
        this.installId = installId;
    }

    public String getInstallId() {
        return installId;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setLastActiveAt(Date lastActiveAt) {
        this.lastActiveAt = lastActiveAt;
    }

    public Date getLastActiveAt() {
        return lastActiveAt;
    }

    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion;
    }

    public String getAppVersion() {
        return appVersion;
    }

}
